/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * Normally generated by `npx convex dev`. At runtime the Convex client resolves
 * `api.module.fn` / `internal.module.fn` references via this proxy.
 */
import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
