/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * Normally generated by `npx convex dev`; committed for offline typechecking.
 */
import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as announcements from "../announcements.js";
import type * as assetOps from "../assetOps.js";
import type * as assets from "../assets.js";
import type * as clerk from "../clerk.js";
import type * as dashboard from "../dashboard.js";
import type * as events from "../events.js";
import type * as files from "../files.js";
import type * as members from "../members.js";
import type * as news from "../news.js";
import type * as publicSite from "../publicSite.js";
import type * as roles from "../roles.js";
import type * as seed from "../seed.js";
import type * as sponsors from "../sponsors.js";
import type * as sync from "../sync.js";
import type * as tags from "../tags.js";
import type * as teams from "../teams.js";
import type * as volunteers from "../volunteers.js";

declare const fullApi: ApiFromModules<{
  announcements: typeof announcements;
  assetOps: typeof assetOps;
  assets: typeof assets;
  clerk: typeof clerk;
  dashboard: typeof dashboard;
  events: typeof events;
  files: typeof files;
  members: typeof members;
  news: typeof news;
  publicSite: typeof publicSite;
  roles: typeof roles;
  seed: typeof seed;
  sponsors: typeof sponsors;
  sync: typeof sync;
  tags: typeof tags;
  teams: typeof teams;
  volunteers: typeof volunteers;
}>;

export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
