export const CAPABILITIES = [
  "settings.admin",
  "roles.manage",
  "invitations.manage",
  "members.read",
  "members.write",
  "members.delete",
  "teams.read",
  "teams.write",
  "teams.delete",
  "events.read",
  "events.write",
  "events.delete",
  "announcements.write",
  "posts.write",
  "posts.moderate",
  "assets.read",
  "assets.operate",
  "assets.admin",
  "volunteers.manage",
  "training.manage",
  "tasks.manage",
  "public_site.manage",
  "sponsors.manage",
  "news.manage",
  "soccer.manage",
  "soccer.grade",
  "audit.read",
  "reports.export",
  "mobile.offline_sync",
  "jobs.dispatch",
  "jobs.complete",
  "fleet.view",
  "fleet.inspect",
  "fleet.manage",
  "fleet.vehicles.manage",
  "fleet.drivers.manage",
  "fleet.jobs.assign",
  "fleet.costs.view",
  "fleet.costs.manage",
  "fleet.costs.approve",
  "fleet.defects.submit",
  "fleet.maintenance.manage",
  "fleet.reminders.manage",
  "fleet.dashboards.view",
  "fleet.export",
  "fleet.templates.manage",
  "fleet.driver_portal",
  "safety.manage",
] as const;

export type Capability = (typeof CAPABILITIES)[number];

export const CAPABILITY_LABELS: Record<Capability, string> = {
  "settings.admin": "Settings administration",
  "roles.manage": "Assign roles",
  "invitations.manage": "Manage invitations",
  "members.read": "View people",
  "members.write": "Create and update people",
  "members.delete": "Delete people",
  "teams.read": "View teams and groups",
  "teams.write": "Create and update teams",
  "teams.delete": "Delete teams",
  "events.read": "View events and jobs",
  "events.write": "Create and update events",
  "events.delete": "Delete events",
  "announcements.write": "Manage announcements",
  "posts.write": "Create posts",
  "posts.moderate": "Moderate posts and comments",
  "assets.read": "View assets",
  "assets.operate": "Operate assets",
  "assets.admin": "Administer assets",
  "volunteers.manage": "Manage volunteers",
  "training.manage": "Manage training",
  "tasks.manage": "Manage tasks",
  "public_site.manage": "Manage public website",
  "sponsors.manage": "Manage sponsors",
  "news.manage": "Manage news",
  "soccer.manage": "Manage sport setup",
  "soccer.grade": "Grade players",
  "audit.read": "View audit logs",
  "reports.export": "Export reports",
  "mobile.offline_sync": "Use mobile offline sync",
  "jobs.dispatch": "Dispatch jobs",
  "jobs.complete": "Complete jobs",
  "fleet.view": "View fleet",
  "fleet.inspect": "Inspect fleet",
  "fleet.manage": "Manage fleet & maintenance",
  "fleet.vehicles.manage": "Manage fleet vehicles",
  "fleet.drivers.manage": "Manage fleet drivers",
  "fleet.jobs.assign": "Assign fleet jobs",
  "fleet.costs.view": "View fleet costs",
  "fleet.costs.manage": "Manage fleet costs",
  "fleet.costs.approve": "Approve fleet expenses",
  "fleet.defects.submit": "Submit fleet defects",
  "fleet.maintenance.manage": "Manage fleet maintenance",
  "fleet.reminders.manage": "Manage fleet reminders",
  "fleet.dashboards.view": "View fleet dashboards",
  "fleet.export": "Export fleet data",
  "fleet.templates.manage": "Manage fleet templates",
  "fleet.driver_portal": "Use driver portal",
  "safety.manage": "Manage safety",
};
