export const CAPABILITIES = [
  "settings.admin",
  "roles.manage",
  "invitations.manage",
  "members.read",
  "members.write",
  "members.delete",
  "teams.read",
  "teams.write",
  "teams.delete",
  "events.read",
  "events.write",
  "events.delete",
  "announcements.write",
  "assets.read",
  "assets.operate",
  "assets.admin",
  "volunteers.manage",
  "training.manage",
  "tasks.manage",
  "public_site.manage",
  "sponsors.manage",
  "news.manage",
  "soccer.manage",
  "soccer.grade",
  "audit.read",
  "reports.export",
  "mobile.offline_sync",
  "jobs.dispatch",
  "jobs.complete",
  "fleet.inspect",
  "safety.manage",
] as const;

export type Capability = (typeof CAPABILITIES)[number];

export const CAPABILITY_LABELS: Record<Capability, string> = {
  "settings.admin": "Settings administration",
  "roles.manage": "Assign roles",
  "invitations.manage": "Manage invitations",
  "members.read": "View people",
  "members.write": "Create and update people",
  "members.delete": "Delete people",
  "teams.read": "View teams and groups",
  "teams.write": "Create and update teams",
  "teams.delete": "Delete teams",
  "events.read": "View events and jobs",
  "events.write": "Create and update events",
  "events.delete": "Delete events",
  "announcements.write": "Manage announcements",
  "assets.read": "View assets",
  "assets.operate": "Operate assets",
  "assets.admin": "Administer assets",
  "volunteers.manage": "Manage volunteers",
  "training.manage": "Manage training",
  "tasks.manage": "Manage tasks",
  "public_site.manage": "Manage public website",
  "sponsors.manage": "Manage sponsors",
  "news.manage": "Manage news",
  "soccer.manage": "Manage sport setup",
  "soccer.grade": "Grade players",
  "audit.read": "View audit logs",
  "reports.export": "Export reports",
  "mobile.offline_sync": "Use mobile offline sync",
  "jobs.dispatch": "Dispatch jobs",
  "jobs.complete": "Complete jobs",
  "fleet.inspect": "Inspect fleet",
  "safety.manage": "Manage safety",
};
